artifacts_root : artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_url : https://github.com/amal-creator/branching-file/raw/refs/heads/main/climate_nasa.zip
  local_data_files : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion


data_validation:
  root_dir : artifacts/data_validation
  STATUS_FILE : artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES : ['train']